FROM python:3.12-slim-bookworm

WORKDIR /app

RUN apt-get update && apt-get install -y build-essential 

COPY pyproject.toml .

RUN pip install --no-cache-dir . 

COPY src/ ./src/

COPY src/config.json ./config.json

EXPOSE 7000

CMD ["fastapi", "run", "webserver.py", "--proxy-headers" ,"--port", "7000", "--host", "0.0.0.0"]


